development:
  adapter: postgresql
  database: users_dev
  host: localhost
  
test:
  adapter: postgresql
  database: users_test
  host: localhost

production:
  adapter: postgresql
  database: users_prod
  host: localhost
